version: 2.0
jobs:
  build:
    docker:
      - image: alpine:3.8
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            apk update
            apk add qt5-qttools-dev git bash python3 composer php7-tokenizer php7-simplexml php7-session php7-dom php7-ctype php7-xml php7-apcu php7-pdo php7-openssl php7-intl php7-gd php7-gettext php7-curl gettext coreutils curl
            python3 -m pip install transifex-client
      - run:
          name: Update Translation Files
          command: |
            ./update_strings
      - run:
          name: Upload Translations
          command: |
            ./.circleci/sync.sh
      - run:
          name: Validate translations
          command: |
            ./validate_locales
