name: CI
on:
  schedule:
    - cron: '0 7 * * 0'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: alpine:3.13

    steps:
      - name: Install Dependencies
        run: |
          apk update
          apk add qt5-qttools-dev git bash python3 py3-pip composer php7-tokenizer php7-simplexml php7-session php7-dom php7-ctype php7-xml php7-apcu php7-pdo php7-openssl php7-intl php7-gd php7-gettext php7-curl gettext coreutils curl
          pip install transifex-client

      - uses: actions/checkout@v2

      - name: Validate translations
        run: ./validate_locales

      - name: Update Translation Files
        run: ./update_strings

      - name: Upload Translations
        run: ./.ci/sync.sh
        env:
          TX_API_KEY: ${{ secrets.TX_API_KEY }}
        if: ${{ !github.base_ref }}
