name: CI
on:
  workflow_dispatch:
    inputs:
  schedule:
    - cron: '0 7 * * 0'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: alpine:3.15

    steps:
      - name: Install Dependencies
        run: |
          apk update
          apk add qt5-qttools-dev git bash composer php8-tokenizer php8-simplexml php8-session php8-dom php8-ctype php8-xml php8-pdo php8-openssl php8-intl php8-gd php8-gettext php8-curl gettext coreutils curl
          curl -sL https://github.com/transifex/cli/releases/download/v1.0.3/tx-linux-amd64.tar.gz -o /tmp/tx.tar.gz
          tar -C /tmp/ -xf /tmp/tx.tar.gz
          cp -v /tmp/tx /usr/local/bin/tx
          ln -sv /usr/bin/php8 /usr/bin/php

      - uses: actions/checkout@v2

      - name: Validate translations
        run: ./validate_locales

      - name: Update Translation Files
        run: ./update_strings

      - name: Upload Translations
        run: ./.ci/sync.sh
        env:
          TX_API_KEY: ${{ secrets.TX_API_KEY }}
        if: ${{ !github.base_ref }}
