name: CI
on:
  workflow_dispatch:
    inputs:
  schedule:
    - cron: '0 7 * * 0'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: alpine:edge

    steps:
      - name: Install Dependencies
        run: |
          apk update
          apk add qt5-qttools-dev git bash composer php81-tokenizer php81-simplexml php81-session php81-dom php81-ctype php81-xml php81-pdo php81-openssl php81-intl php81-gd php81-gettext php81-curl gettext coreutils curl
          curl -sL https://github.com/transifex/cli/releases/download/v1.6.5/tx-linux-amd64.tar.gz -o /tmp/tx.tar.gz
          tar -C /tmp/ -xf /tmp/tx.tar.gz
          cp -v /tmp/tx /usr/local/bin/tx
          rm -v /usr/bin/php
          ln -sv /usr/bin/php81 /usr/bin/php

      - uses: actions/checkout@v3

      - name: Validate translations
        run: ./validate_locales

      - name: Update Translation Files
        run: ./update_strings

      - name: Upload Translations
        run: ./.ci/sync.sh
        env:
          TX_API_KEY: ${{ secrets.TX_API_KEY }}
        if: ${{ !github.base_ref }}
