name: CI
on:
  workflow_dispatch:
    inputs: {}
  schedule:
    - cron: '0 7 * * 0'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:rolling

    steps:
      - name: Install Dependencies
        run: |
          apt-get update
          apt-get install -y qttools5-dev-tools git bash composer php8.2-cli php8.2-intl php8.2-xml php8.2-curl php8.2-gd gettext curl
          curl -sL https://github.com/transifex/cli/releases/download/v1.6.10/tx-linux-amd64.tar.gz -o /tmp/tx.tar.gz
          tar -C /tmp/ -xf /tmp/tx.tar.gz
          cp -v /tmp/tx /usr/local/bin/tx

      - uses: actions/checkout@v3

      - name: Validate translations
        run: ./validate_locales

      - name: Update Translation Files
        run: ./update_strings

      - name: Upload Translations
        run: ./.ci/sync.sh
        env:
          TX_API_KEY: ${{ secrets.TX_API_KEY }}
        if: ${{ !github.base_ref }}
